title:            Oasis
description:      You can bring a horse to water, but you can\t make him drink.
url:              blog.brianseitel.com
signoff:          Brian
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://blog.brianseitel.com
    external:     true
  - name:         Email
    url:          mailto:brianseitel@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/brianseitel
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
